### PR TITLE
Improve linking to the required courses

### PR DESCRIPTION
**Pull request by amit-tewari**
These changes work for my use case.
But this may not be how other users or you would like this to be implemented. Please feel free to modify this PR to fit well with plugin design.

Also, I was not sure of the contribution flow, thus created PR against branch MOODLE_400_STABLE.

Details in:
https://github.com/ewallah/moodle-enrol_coursecompleted/issues/30

### CODE REVIEW

**Comment by ewallah** [comment]
All above checks failed because the string does not exist.

`{{#str}} coursecompletedprereqmsg {{/str}}`
should be
`{{#str}} coursecompletedprereqmsg, enrol_coursecompleted{{/str}}`

But isn't it much simpler that you, in your instance, change the language entry [willbeenrolled](https://docs.moodle.org/402/en/Language_customisation). You could change the current language string into; `You will be enrolled in this course when you complete course {$a}<br>Choose and complete required course(s) first.<br/>Click on the circles to choose a pre-requisite course.` to have the same effect. Anyhow I will ask for extra feedback to several teachers if they like the addition.

I personally, but also Moodle,  avoid language strings as 'click on the'... Perhaps you could see the  presentation about accessibility by #gavinhenrick on [YouTube](https://www.youtube.com/watch?v=AqQawzxCz1c&pp=ygUnbW9vZGxlbW9vdCAyMDIyIGJhcmNlbG9uYSBhY2Nlc3NpYmlsaXR5)

**Comment by amit-tewari** [comment]
@ewallah ,
Thank you for the review. Fixed the error as suggested, by combining string into one.
I shall go through the video, but in the mean time feel free to incorporate any changes as seen fit from broader user community point of view. I trust you and the other long term developers/ users making right choices.

**Comment by ewallah** [comment]
Hello @amit-tewari,

Sorry, but I will not accept your pull request. And this for 2 reasons:

1. The change from enrol/index.php into course/view.php does not handle well people who are not logged in. The enrol/index.php immediately refers to the course/view.php file when somebody is logged in, but shows the enrolment page to guests. So I see a loss in functionality in your submit.
2. The language changes should not be done in the plugin, but in [AMOS](https://lang.moodle.org/). Because your suggestions limit sites to customize: a theme can change the circles into stars or squares so the text 'click on the circles' would become wrong. I suggest you modify your site using language customization (Site administration > Language > Language customisation ).

**Comment by ewallah** [comment]
After all, your proposal to change enrol/index.php to course/view.php was accepted and added to the code.

THX for your work.

**Comment by amit-tewari** [comment]
It was a pleasure working with, and learning from, you @ewallah through this small improvement.
Thanks again to the plugin maintainers for maintaining this very useful tool for a large community.

**Pull request closed without merging**
