### PR TITLE
translation to spanish

### PR DESCRIPTION
**Pull request by fperaza83**
translation to spanish

### CODE REVIEW

**Comment by ewallah** [comment]
THX for your work, but translations are done in AMOS (https://lang.moodle.org). 
Please submit your work there.

**Comment by fperaza83** [comment]
Hi, thanks!  I didn't knew that.

**Comment by ewallah** [comment]
My Spanish is not 100%, so a native speaker should review your work.

When you register and submit your work on Amos, somebody else will review your work and accept or reject your translations. A day or so later, all Moodle users will benefit from your work!

**Comment by fperaza83** [comment]
Thank you, I will do that.

**Pull request closed without merging**
