### PR TITLE
Optionally add a continue button

### PR DESCRIPTION
**Pull request by andrewhancox**
Currently the only navigation option when not enrolled is to navigate up the tree of dependent courses which my client felt was a bit of a navigational black hole.
This patch allows you to show a continue button that will return to the referrer or course home page.

### CODE REVIEW

**Comment by ewallah** [comment]
Hello Andrew,

THX for the pull request.  I like the idea but I need some time to let it sink in.

Some questions:

- why did you call it a continue button when it seems to me more a 'return to' button?
- is this the best solution in complex situations where different enrolments are enabled? 
- can you also write PHPUnit and Behat tests to check the functionality of the code?  Tests are a blessing when Moodle code or PHP changes.

R

**Comment by andrewhancox** [comment]
I totally get why you're wanting to think about it. My thoughts are:

If you look at enrol/index.php
"foreach($enrolinstances as $instance) {" around line 73
"if (!$forms) {" somewhere around line 110
Where all enrolment plugins enrol_page_hook functions return false it shows a continue button to return the user to where they came from in order to prevent them being stuck in a navigational dead end.

The moodle-enrol_coursecompleted plugin returns text from the enrol_page_hook function which tells the user why they could not be enrolled and gives them an option to navigate to the pre-requisite course which is useful but stops the normal continue button from being shown by the core code. What I've done is to re-implement this button with some minor tweaks to avoid users getting stuck in a loop. This is why the button is still called continue. By default the functionality is disabled but it can be enabled in a flexible way (site default, overridden per instance) so if there was a complex situation with multiple plugins you would definitely configure it to not be shown.

I didn't think to look to see if you have automatic tests, if you decide to integrate this PR I will write a couple of unit tests.

**Comment by ewallah** [comment]
I tried to test your pull request.  For the moment I simplified things, but the global idea remains.

However I get a redirect: students are getting a warning:  You are already logged in as....   You can see this redirect to the login page behavior in the [behat test](https://github.com/ewallah/moodle-enrol_coursecompleted/blob/1b2594ab8e29c2d846f97e731791cf6056c7e8d0/tests/behat/coursecompleted_continue.feature#L70).

Continue button:
Continue-button-in-enrolment-on-course-completion2

Redirect page:
Continue-button-in-enrolment-on-course-completion

**Comment by ewallah** [comment]
Closed due to
- solution is NOT working
- lack of feedback

**Pull request closed without merging**
